### PR TITLE
Change developer bio text

### PR DESCRIPTION
**Pull request by kaushikhande**
## Pull request checklist

[Issue-560](https://github.com/joemasilotti/railsdevs.com/issues/560)

- [x] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [x] I added significant changes and product updates to the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by kaushikhande** [comment]
@joemasilotti Please review

**Comment by joemasilotti** [comment]
Thanks for the contribution, @kaushikhande! Where did you source the non-English translations?

**Comment by kaushikhande** [comment]
> Thanks for the contribution, @kaushikhande! Where did you source the non-English translations?

Google translate

**Comment by joemasilotti** [comment]
Got it. Can you please remove those translations then? I'd rather have no translation at all vs. something from Google Translate right now.

**Comment by kaushikhande** [comment]
> Got it. Can you please remove those translations then? I'd rather have no translation at all vs. something from Google Translate right now.

Okay. Removing

**Comment by kaushikhande** [comment]
@joemasilotti Please review. Translation removed

**Comment by joemasilotti** [comment]
Awesome – thanks for your contribution!

**Pull request merged**
