### PR TITLE
Hide icons in `new` roles from screen readers

### PR DESCRIPTION
**Pull request by crabbits**
This PR addresses the issue #551 

I've passed the `aria_hidden: true` option to all `inline_svg_tag` helpers in the `roles/new.html.erb` view. Also added a new integration test to check both options on the `role/new` page and check all svgs in the main DOM element have `aria-hidden=true` set. 

@joemasilotti @metamoni it might be worth me writing a helper to wrap the `inline_svg_tag` helper so `aria_hidden: true` is always passed in by default as I'm sure this is happening on other pages (such as #554)

Also @joemasilotti let me know if you're happy with the approach of passing the option into the `inline_svg_tag` helper vs adding `aria_hidden=true` to the parent `<span>`'s, not sure which one you prefer / will be easier to maintain going forward.

- [x] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [ ] I added significant changes and product updates to the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by crabbits** [comment]
Woops not sure what happened to the CI build, I'll fix it sorry :(

**Comment by crabbits** [comment]
@joemasilotti I also got a `[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called` error while running bin/check, seems to be an [issue](https://github.com/rails/rails/issues/38560) with M1 Macs, would you like me to update the README in the test section to make a note of it?

**Comment by joemasilotti** [comment]
> I've passed the `aria_hidden: true` option to all `inline_svg_tag` helpers in the `roles/new.html.erb` view. Also added a new integration test to check both options on the `role/new` page and check all svgs in the main DOM element have `aria-hidden=true` set. 

No need for the integration test! Feel free to remove that.

> @joemasilotti @metamoni it might be worth me writing a helper to wrap the `inline_svg_tag` helper so `aria_hidden: true` is always passed in by default as I'm sure this is happening on other pages (such as #554)

Great idea. Let's add a helper that does exactly that. `aria_hidden_inline_svg_tag` or `non_interactive_inline_svg_tag`, maybe?

Even better... `icon_tag` and `decorative_icon_tag` could wrap the exiting helper and clean up the repeated filename string a bit!

```ruby
<%= decorative_icon_tag "briefcase", :outline, class: "..." %>
<%= icon_tag "mail", :solid, class: "..." %>
```

> Also @joemasilotti let me know if you're happy with the approach of passing the option into the `inline_svg_tag` helper vs adding `aria_hidden=true` to the parent `<span>`'s, not sure which one you prefer / will be easier to maintain going forward.

If we go with the helper above that will always set it on the SVG directly. I'm inclined to go with that since we won't ever have to set it manually by using the two different helpers.

**Comment by crabbits** [comment]
> No need for the integration test! Feel free to remove that.

Easy will do

> Great idea. Let's add a helper that does exactly that. aria_hidden_inline_svg_tag or non_interactive_inline_svg_tag, maybe?
>
> Even better... icon_tag and decorative_icon_tag could wrap the exiting helper and clean up the repeated filename string a bit!

I like this approach, will play around with it once I'm off work.

> What version of Ruby are you running for that to appear? The thread hints at this being fixed in a recent release.

I'm running `3.1.2`, but it may be something weird with my setup, will leave it for now.

**Comment by joemasilotti** [comment]
@metamoni, would love to hear your expertise here. Is there a difference (or recommended approach) for these two options?

```html
<span class="text-blue-500" aria-hidden="true">
  <svg src="/icons/mail.svg"></svg>
</span>
```

```html
<span class="text-blue-500">
  <svg src="/icons/mail.svg" aria-hidden="true"></svg>
</span>
```

**Comment by joemasilotti** [comment]
Hey @crabbits, apologies for overwriting some of your changes with my recent push. But I realized that we don't need anything fancy like what I was prescribing earlier. I opted to add a single option to each `inline_svg_tag` to make them hidden to screen readers.

Thanks for kicking off the work on this!

**Comment by benmercerdev** [comment]
> @joemasilotti I also got a `[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called` error while running bin/check, seems to be an [issue](https://github.com/rails/rails/issues/38560) with M1 Macs, would you like me to update the README in the test section to make a note of it?

Were you able to resolve this? Also running into the same issue. M1 Mac here as well

**Pull request merged**
