### PR TITLE
Update logo in header

### PR DESCRIPTION
**Pull request by joemasilotti**
Before you submit a pull request for review, please make sure...

- [ ] Your code contains tests relevant for code you modified
- [x] All new and existing tests are passing
- [x] You have linted the project `bundle exec standardrb --fix`

If this PR is not ready for review, please make sure to submit it as a draft.

### CODE REVIEW

**Comment by joemasilotti** [comment]
New logo WIP!

railsdevs

**Comment by gathuku** [comment]
Hey @joemasilotti  which tool are you using to make the logo?

**Comment by joemasilotti** [comment]
Sketch.app

https://www.sketch.com/

**Comment by gathuku** [comment]
Thank you

**Pull request merged**
