### PR TITLE
Clean up ignored i18n keys

### PR DESCRIPTION
**Pull request by pkayokay**
- Removes smart comments that mark translations as used 
- Issue https://github.com/joemasilotti/railsdevs.com/issues/313

## Pull request checklist

- [ ] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [x] I added significant changes and product updates to the [changelog](CHANGELOG.md)

### CODE REVIEW

**Review by joemasilotti — CHANGES_REQUESTED** [review]
From the issue,

> The overall goal of this issue is to remove all of the inline comments marking translations as used. Devise is already listed in the i18n-tasks configuration, so no adjustments to Devise translations should be needed.

> I'm more interested in removing the smart comments sprinkled throughout the app that tell i18n-tasks we are using a translation.

**Comment by pkayokay** [comment]
Oh. I misread the intent, did the initial intent change? (along with the original PR work), so reverting what is on https://github.com/joemasilotti/railsdevs.com/pull/385

**Comment by joemasilotti** [comment]
#385 was a stop-gap to ensure `bundle exec i18n-tasks health en` would pass. The end goal of the original issue is to remove the magic comments as much as possible and handle the dynamic-ness of the translations in the configuration file.

**Comment by joemasilotti** [comment]
Hey @pkayokay, I'm going to close this because I haven't heard anything in a few weeks. Feel free to re-open it if you have the appetite!

**Pull request closed without merging**
