### PR TITLE
Link to conversations from developer and business pages #602

### PR DESCRIPTION
**Pull request by xmarlox**
Link to conversations from developer and business pages #602

* Use grid for pills button with 3 actions per row in Admin section of developer & business profile pages
* Change the link of developer & business to its corresponding show/profile page in Users list page

## Pull request checklist

- [x] I linted and tested the project with `bin/check`

### CODE REVIEW

**Comment by joemasilotti** [comment]
Thanks for your contribution!

I'm having second guesses on if the two rows of pills is the right approach now. I wouldn't have known it without seeing it, so thanks for taking the time to wire it up!

Let's revert back to the single pill of 3 buttons. And add a link to "View conversations" underneath them. I think this makes more sense both visually and behaviorally - actions do things and links visit a page.

I understand I took a while to review this PR. Let me know if you still have appetite to take it over the finish line. If not, no worries! I can take over.

**Comment by xmarlox** [comment]
@joemasilotti 
it's ok, i can change it accordingly.

**Comment by xmarlox** [comment]
@joemasilotti just addressed your PR comments. let me know if there still need to change.
thanks! 😃

**Comment by joemasilotti** [comment]
@xmarlox, do you still have appetite to finish this? If not, no worries! I can assign it to someone else.

If I don't hear back in a few days I'll close this PR.

**Pull request closed without merging**
