### PR TITLE
Update es.yml

### PR DESCRIPTION
**Pull request by michelson**
some corrections on Spanish translations

### CODE REVIEW

**Comment by joemasilotti** [comment]
Thanks for this! I appreciate it. 

Do you have any appetite to translate some more of the English file to Spanish?

**Comment by michelson** [comment]
sure! how do you sync the files?

**Comment by michelson** [comment]
@joemasilotti, maybe it should be a good idea to apply for an open-source account for https://crowdin.com/, I'm using that already on https://github.com/chaskiq/chaskiq/, and it syncs with PR every time someone contributes with some languages.

**Comment by joemasilotti** [comment]
I just signed up for an account with crowdin. Do you have any insight or tutorials on how to integrate with the codebase?

P.S. I had no idea that chaskiq was yours! I've been looking into a live-chat support... thingy and wanted to go OSS if possible.

**Comment by michelson** [comment]
Hi Joe, I've submitted a PR here #532 that will do the work. I've added some notes too. send us the crowding link I will be glad to help on the Spanish one.

> P.S. I had no idea that chaskiq was yours! I've been looking into a live-chat support... thingy and wanted to go OSS if possible.

😅 yeah! let me know if you want to try it out so I can give you a free account on my instance.

**Pull request merged**
