### PR TITLE
Messaging

### LINKED ISSUE #120: A business can message a developer
The ~first~ second (of many) [Messaging](https://github.com/joemasilotti/railsdevs.com/projects/3) issues!

A PR addressing this issue should...

* Add a Message button to a developer's profile
    * When clicked, if signed in as a business then open a new conversation screen
    * When clicked, if not signed in as a business then prompt to create a business profile
* `developers/:id/messages/new` with an input field
    * Create a `Conversation` that belongs to the developer and business
    * Create a `Message` that belongs to the conversation
    * Can only be access by a business (via `pundit`)
* `conversations` index of all conversations the developer or business is a part of (read only)
    * Link to conversations from header / menu
* `/developers/:id/conversation` show a specific conversation (read only)
    * `pundit` for authorization scopes
* Hide the Message button in production based on the feature flag
* Double check mobile views

### PR DESCRIPTION
**Pull request by joemasilotti**
This PR addresses #120, #121, and #122. I tried to split this into 3 PRs, but I ended up rewriting so much of #130 that I don't think it is worth keeping them separate anymore.

All of the refactors from #130 have been pulled in, so check out that PR for details on the pundit changes.

I ended up simplifying the routes a ton to get the base functionality working. Instead of trying to nest conversations inside of developers, the route is more Rails-y: `/conversations/:id`. This helps clean up the controller logic a ton.

On top of that, to ensure only a `Business` can initiate a conversation, `ColdMessagesController` was added. This includes the logic for kicking off that first message and redirecting to an existing conversation if one exists.

### Room for improvement / future PRs

* The `Message` form at the bottom of the conversation page could be Turbo-ified
* The new `Business` page is very barebones, and could use another design pass
    * There's probably new fields a `Business` wants to add, too

### Pull request checklist

- [x] Your code contains tests relevant for code you modified
- [x] All new and existing tests are passing
- [x] You have linted the project with `bundle exec standardrb --fix`
- [x] You have linted the project with `bundle exec erblint --lint-all --autocorrect`

Closes #120, #121, and #122.

### CODE REVIEW

**Comment by joemasilotti** [comment]
Instead of inferring intent, or having a user toggle, we can have two different URLs.

* `/developer/conversations` - index page for businesses (messaging developers)
* `/businesses/conversations` - index page for developers (messaging businesses)

**Comment by joemasilotti** [comment]
Unless I'm missing something, that `erblint` is a false positive.

https://github.com/Shopify/erb-lint/issues/244

**Comment by joemasilotti** [comment]
CC @jacobdaddario and @Tonksthebear because you both expressed interest in these features. Would love to hear your thoughts or quick PR review before I merge.

**Comment by jacobdaddario** [comment]
Hey! Sorry I've been occupied with some other stuff recently. I'll take a look this evening!

**Comment by Tonksthebear** [comment]
Hey, I have a lot on my plate this week. I might be able to hop on and take a look, but I just wanted to acknowledge your message and give you a heads up to not wait on me. I will definitely take a look if I get a chance though!

**Comment by jacobdaddario** [comment]
Hey, sorry for not getting to this yesterday. Life has still been kicking my butt. I'll attempt to get to it tonight.

**Comment by jacobdaddario** [comment]
Looks good to me! I think there's things I would have approached a different way, but the logic you laid out all seems to make sense.

**Pull request merged**
