### PR TITLE
added logic to messaging_policy with business privileges and added f… #358

### PR DESCRIPTION
**Pull request by GALTdea**
I have a couple of questions regarding your specs: 
1) Show a warning/info message and disable the form on the cold message page and conversation page
- Do you want the part-time business account user to have access to the message view? or can the be redirected upon clicking the "Hire Me" link on the developer show page?  

…ull_time method to user.rb

### Pull request checklist

- [ ] Your code contains tests relevant for code you modified
- [ ] You have linted and tested the project with `bin/check`
- [ ] You have added significant changes and product updates to the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by GALTdea** [comment]
I don't think i was supposed to open a new (draft) PR. IN any case, I just wanted to open up a draft because I had  questions regarding your specs. "Show a warning/info message and disable the form on the cold message page and conversation page"
Do you want the part-time business account user to have access to have access to the message(s) pages? or can they be redirected upon clicking the "Hire Me" link on the developer show page?

**Comment by joemasilotti** [comment]
> Do you want the part-time business account user to have access to have access to the message(s) pages? or can they be redirected upon clicking the "Hire Me" link on the developer show page?

The part-time business should have access to the cold message view but the form should be disabled with the warning message being shown. The `Messaging` policy should also enforce _creating_ a message for that business to that developer in case someone gets clever and POSTs directly to the endpoint bypassing the form.

**Comment by GALTdea** [comment]
Ok, I should be getting closer but I'd like for you to take a look at my approach to disabling the form. basically i created a variable '@disabled' in the controller to keeps track on its given Policy.   Currently trying to figure out how not to redirect from the new view and and show the warning message instead when businesses are denied. 
looks like pundit recognizes it from the en.yml if i use the policy/method name as a key? i'll give it a try in the morning. That would solve for redirect to since I would not use the new? method.

**Comment by joemasilotti** [comment]
I took a pass at reworking some of your code with a new approach. I'm trying a new policy, `SubscriptionPolicy`, that isn't called via `authorize`. Instead, the method is called directly. Yes, it kind of defeats the purpose of Pundit but it does keep all the policy-like code in the same directory.

I'm doing this so we don't raise the Pundit exception but set an instance variable to true/false. Alternatively, we could raise and display the message in an alert back on the developer page. But it might be hard to tap into the message output because we would need HTML.

Anyway, here's what's left to get this deployed:

- [ ] Add test for when @messageable is false in ColdMessagesTest.
- [ ] Add test for when @messageable is false in MessagesTest.
- [ ] Add tests for SubscriptionPolicy.
- [ ] Authorize SubscriptionPolicy in MessagesController#create.

**Comment by joemasilotti** [comment]
Making progress here, only two things left I think:

- [ ] Show error alert in place of form on `Conversations#show`
- [ ] Ensure updating a plan via Stripe Billing Portal is reflected in database

**Comment by GALTdea** [comment]
The new messaging_policy makes a lot more sense than my method on messaging_policy.  I am glad you added the messaging. I spent a couple days trying to figure how to enforce the messaging from the policy, pundit's not very flexible with customizing exceptions

**Comment by joemasilotti** [comment]
OK, I think this is good to go! Everything is working as I expect it to and all the tests are green. I'm going to give the code another review tomorrow (or later this week) and merge it in.

**Comment by joemasilotti** [comment]
Thanks for kicking this off, @GALTdea!

**Pull request merged**
