### PR TITLE
Update rails to 7.0.4

### PR DESCRIPTION
**Pull request by kaushikhande**
Update to Rails 7.0.4 Issue [#682 ](https://github.com/joemasilotti/railsdevs.com/issues/682)

## Pull request checklist

- [ ] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [x] I added significant changes and product updates to the [changelog](CHANGELOG.md)
- [x] Upgrade the codebase to Rails 7.0.4
- [x] Review the [changelog](https://github.com/rails/rails/releases/tag/v7.0.4) and ensure nothing breaks

### CODE REVIEW

**Comment by kaushikhande** [comment]
@joemasilotti Please review this PR.
Regarding your second checklist mentioned on the issue, I think there are no breaking changes in 7.0.4. Do you feel  [Changelog](https://github.com/rails/rails/releases/tag/v7.0.4) has any breaking changes

**Comment by joemasilotti** [comment]
Excellent! Nothing jumped out to me so I think we are good to merge.

Can you please update the date to August 11 (from August 10) in the CHANGELOG?

**Comment by kaushikhande** [comment]
@joemasilotti Done with changelog changes. Please review it again.

**Comment by joemasilotti** [comment]
Looks great, thanks for your contribution!

**Pull request merged**
