### PR TITLE
Conversation scroll

### PR DESCRIPTION
**Pull request by jasonplatts**
Pull request adds scrolling to the message form when the conversation page loads.

### Pull request checklist

- [X] Your code contains tests relevant for code you modified
- [X] You have linted and tested the project with `bin/check`

### CODE REVIEW

**Comment by joemasilotti** [comment]
Thanks for this! I love the idea of scrolling to the bottom when loading a conversation.

But I'm wondering if this is possible without JavaScript. For example, can we use an anchor to have the browser automatically scroll to the message form at the bottom?

**Comment by jasonplatts** [comment]
No problem. Thank you for reviewing the pull request! You had a great suggestion. I tried to implement it, but ran into a couple of issues.

First, Turbo seems to be interfering with navigating to the anchor. It will initially jump to the correct location, then reload and jump to the top of the page again. The screen below shows the behavior when clicking on the conversation link generated by this code, `link_to conversation_path(conversation, anchor: "message_body")`

anchor-example

The second issue is that it doesn't seem to be possible to include the anchor with the submission of the message form without using JavaScript.

Do you have any thoughts or suggestions?

**Comment by joemasilotti** [comment]
Huh, good to know! Do you know if this is a documented bug or something with the configuration/rendering of railsdevs?

**Comment by jasonplatts** [comment]
Hi Joe. I sent you a message on this PR. When the form was hotwired, the scrolling stopped working on the initial page load. I'm trying to get some help figuring out the problem.

**Comment by jasonplatts** [comment]
Sorry Joe. This is not a problem with the turbo frame, but rather turbo in general I think.

See below:
2022-03-30 - railsdev com scroll issue

**Comment by joemasilotti** [comment]
Shout out to @ParamagicDev for helping me get this one over the finish line!

**Pull request merged**
