### PR TITLE
added search status filter to developers page

### PR DESCRIPTION
**Pull request by themudassarhassan**
This PR adds the ability to filter developers by search status.
Related [issue](https://github.com/joemasilotti/railsdevs.com/issues/236)
### Pull request checklist

- [x] Your code contains tests relevant for code you modified
- [x] You have linted and tested the project with `bin/check`

### CODE REVIEW

**Comment by joemasilotti** [comment]
Hey @themudassarhassan, thanks for the PR! Would it be possible to also add in the "role type" search fields to the dropdown? After playing with the UI I think those are actually a bit more important. Then we can also drop "not interested" because I don't think it provides much value, to be honest. Something like the screenshot with a dividing line between the 2nd and 3rd option would be great!

image

Let me know if this makes sense and you have the appetite to work on it. If not, no worries, I can take your PR and finish it up.

**Comment by themudassarhassan** [comment]
Hey @joemasilotti Thanks for the feedback! Yeah that makes sense. I'll work on this.

**Comment by themudassarhassan** [comment]
@joemasilotti I have pushed the changes. Please have a look when you get some time. Thanks!

**Comment by joemasilotti** [comment]
Thanks again for the PR! I reworked the filtering a tad to instead:

* always filter out developers who are "not interested" (or blank) search status
* an option to show them in the dropdown

All that's left is a CSS fix to make this text wrap (it's too long) and a final review!

image

**Comment by themudassarhassan** [comment]
Great! Do you want me to fix that CSS?

**Comment by joemasilotti** [comment]
If you can, yes please! I'm struggling to find a fix myself. Ideally, it would wrap to put "interested" on the second line.

**Pull request merged**
