### PR TITLE
Add zh-CN locale

### PR DESCRIPTION
**Pull request by renny-ren**
## Pull request checklist

- [ ] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [ ] I added significant changes and product updates to the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by joemasilotti** [comment]
Thanks for your PR!

I'm hesitant to merge this until the rest of the translations are added. Only having a few doesn't help folks much, in my opinion.

Do you have appetite to finish the rest?

**Comment by renny-ren** [comment]
Sure, I'll add the rest soon.

**Comment by renny-ren** [comment]
Hi @joemasilotti , I've added the rest of the translations.

**Comment by joemasilotti** [comment]
Thanks! One question and one request:

1. Did you translate the copy manually or was any of it automated?
2. Please remove the English translations from this file. The app will default back to English for anything missing.

**Comment by renny-ren** [comment]
> Thanks! One question and one request:
> 
> 1. Did you translate the copy manually or was any of it automated?
> 2. Please remove the English translations from this file. The app will default back to English for anything missing.

I translated it manually, it's not automated. And all English translations are removed.

**Comment by joemasilotti** [comment]
Excellent! Thanks so much for your contribution :)

If you have a RailsDevs profile please link it here so I can add the "Source contributor" tag to your profile.

**Comment by renny-ren** [comment]
Thanks! Here is my link: https://railsdevs.com/developers/BbVXUYa0/73730d7f

**Comment by joemasilotti** [comment]
And done!

image

**Pull request merged**
