### PR TITLE
create referrals page in admin

### PR DESCRIPTION
**Pull request by hafezbusra**
## Pull request checklist

- [x] My code contains tests covering the code I modified
- [ ] I linted and tested the project with `bin/check`
- [x] I added significant changes and product updates to the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by joemasilotti** [comment]
Is this PR ready for review or are you still working on it?

**Comment by hafezbusra** [comment]
@joemasilotti not yet im sorry it took longer time to finish im not familiar yet with how stimulus and turbo to work. Still working on the search function for creating new referral

**Comment by joemasilotti** [comment]
Gotcha, no worries! Can you please convert this PR to a draft? Then when it is ready you can mark it as such.

And I don't think you should need any Stimulus to work on this issue, or Turbo for that matter. But let me know if I'm missing something.

**Comment by joemasilotti** [comment]
I won't be able to merge anything until the tests are passing and either a) the feature is complete or b) incomplete code is behind a feature flag.

Let me know if you'd like me to take over and I can finish it up.

**Comment by hafezbusra** [comment]
hi @joemasilotti ive request to merge, for the creating and updating referral is it urgent? i would like to try but im not available currently.

**Comment by hafezbusra** [comment]
if its urgent i think you can take over

**Comment by joemasilotti** [comment]
Ok cool. I’ll review today. Thanks!

**Review by joemasilotti — APPROVED** [review]

**Comment by joemasilotti** [comment]
Thanks for kicking this off @hafezbusra! I moved one of the controller methods to a new, namespaced controller and added a "View" link to the index page.

I'm going to merge this in once CI passes.

**Comment by hafezbusra** [comment]
Thanks also @joemasilotti for this opportunity, i would like to try more in the future

**Pull request merged**
