### PR TITLE
Added remote work preference

### PR DESCRIPTION
**Pull request by dqnamo**
Hey 👋🏽 This is my first PR here. I had only noticed after publishing the branch that the process is to comment on the issue first. Will do this in the future. The issue this PR addresses is #346 

I have done a little bit more than what the issue had said but let me know if it is overkill and we can scale it back. I Have added three options for remote work. `remote_only` `remote_preferred` and `no_preference`. These can be filtered through aswell.
CleanShot 2022-07-11 at 20 46 23@2x
CleanShot 2022-07-11 at 20 29 49@2x

### Some other points:
- Wasn't fully sure about "Finally, letting the business know before reaching out that the developer is only interested in remote roles. (Perhaps in ColdMessagesController#new.)" from the issue. 
- I have added a query filter test but wasn't sure if this was enough.
- The locales for Spanish and Portuguese, I have added through google translate. Not sure how accurate this is!
- The wording on the remote work preference might be a bit confusing, especially when looking at the filter through a business perspective it might seem that its indicating the preference of the business hiring.
- Potentially could remove the no preference option, what do you think?

## Pull request checklist

- [x] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [ ] I added significant changes and product updates to the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by joemasilotti** [comment]
Thanks for the PR! Can you please comment on #346 so I can assign it to you?

I haven't dove into the code yet, but here are my thoughts on your questions.

First, let's open this up a bit more to work location in general. We can change the section header to "Location" and make the options checkboxes instead of a radio. Then, these options might make a bit more sense:

* In-person
* Remote
* Hybrid
* Willing to relocate

> Wasn't fully sure about "Finally, letting the business know before reaching out that the developer is only interested in remote roles. (Perhaps in ColdMessagesController#new.)" from the issue.

Don't worry about this for now.

> The locales for Spanish and Portuguese, I have added through google translate. Not sure how accurate this is!

Please remove any translations from Google Translate.

**Comment by joemasilotti** [comment]
Yeah, a new model sounds right. Good idea!

**Comment by dqnamo** [comment]
@joemasilotti quick question,  In the developer form the title 'location' works but in the filters there is already a 'location' titled filter so how exactly do we want to reconcile this?
CleanShot 2022-07-18 at 20 15 24@2x
CleanShot 2022-07-18 at 20 15 32@2x

**Comment by joemasilotti** [comment]
I'm thinking we can add another subheading for "Preference" with these options that doesn't collapse.

**Comment by joemasilotti** [comment]
Hey @dqnamo, do you still have appetite to finish this one?

If not, no worries. Let me know and I can take it from here.

**Comment by dqnamo** [comment]
Hey @joemasilotti Yeah I got quite busy with some other work, so yeah maybe might be better if you take this one. Will try to maybe do a smaller issue PR when I can.

**Comment by joemasilotti** [comment]
I resolved the conflicts and merged in `main`. But I don't think I'm going to merge this in anytime soon.

Thanks for kicking it off, @dqnamo! I'll re-open this PR if/when we want to revisit this.

**Pull request closed without merging**
