### PR TITLE
Tidy up word wrap on developer cards

### LINKED ISSUE #134: Tidy up word wrap on developer cards
The developer bio is cut off at weird-looking lines on desktop vs. mobile. The homepage, on desktop, limits the bio to a single line. But 2 lines are visible on mobile.

Also, the word wrap of the developer hero is being wrapped on characters which makes for some heroes hard to read. This should instead break on words.

image

image

### PR DESCRIPTION
**Pull request by danieldpence**
👋🏻 Cool project, thought I'd give this a shot real quick.

I went with max 3 lines of text on mobile and desktop since the cards seemed to have room to allow for 3 lines. You may have plans to add additional data beneath the bio at some point, I don't know.

Closes #134 
Screen Capture on 2021-12-08 at 10-10-41

### Pull request checklist

- [x] Your code contains tests relevant for code you modified
- [x] All new and existing tests are passing
- [x] You have linted the project with `bundle exec standardrb --fix`
- [x] You have linted the project with `bundle exec erblint --lint-all --autocorrect`
- [x] You have linted the project with `bundle exec i18n-tasks health`

### CODE REVIEW

**Comment by joemasilotti** [comment]
Fancy seeing you here!

Thanks for the PR. Can you please screenshot a developer hero with a very long word?

If that looks good then we can merge!

**Comment by danieldpence** [comment]
@joemasilotti That's a good point, and tricky to solve. After playing with various ideas, this seems to best I could come up with so far. How's this feel?

Clamping to 1 line + `title` attribute for an easy way to view the full hero on hover (maybe tooltips in the future?).
Screen Capture on 2021-12-08 at 13-25-21
Screen Shot 2021-12-08 at 1 34 55 PM

**Comment by joemasilotti** [comment]
Good call with the title. I like this. My concern is that a single line is not enough info, though. Let's clamp to 2 lines and, assuming it all looks good, merge this in!

**Comment by danieldpence** [comment]
@joemasilotti yeah, I agree with your concern, for sure, but clamping to 2 lines results in horizontal overflow when you have super long words, which you can counter with `break-all`, but I don't think you want words breaking to a new line in the middle of a word.

`line-clamp-2 break-word`:
Screen Shot 2021-12-08 at 4 33 28 PM

`line-clamp-2 break-all`:
Screen Shot 2021-12-08 at 4 34 27 PM

**Comment by joemasilotti** [comment]
What about line clamp 2, word break, and hidden horizontal overflow?

**Comment by danieldpence** [comment]
I tried that, actually. `line-clamp` includes `overflow: hidden`. The problem is, the hero doesn't have a fixed width, nor does it have a parent element with a defined width, so long words continue to grow without _overflowing_ any parent element (since it's the hero determining the width of the parent).

I'll keep playing with it and see if I can come up with another solution, unless you have other ideas.

**Comment by joemasilotti** [comment]
Weird! But good to know. 

I think the card has a max width. What if we changed that to an explicit width? Or added `w-full`?

**Comment by danieldpence** [comment]
@joemasilotti Turns out it was a flexbox issue, and setting `min-width-0` on one of the parent containers solved the issue. We don't get the ellipsis on long words with the overflow hidden, but hopefully those will be the exception and not the rule.

Screen Capture on 2021-12-08 at 20-02-24

**Comment by joemasilotti** [comment]
Amazing! Great find. I'll merge this in as soon as CI passes. Thanks for your contribution :D

**Pull request merged**
